config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "brackets#new"

  resources :brackets, only: [ :index, :new, :show, :update ]

  # API routes
  namespace :api do
    resources :brackets, only: [ :create, :show ]
  end

  resources :players

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/bracket.rb
class Bracket < ApplicationRecord
  has_many :bracket_entries

  validates :user_identifier, presence: true

  # after_initialize :initial_entries

  def initial_entries
    # bracket_entries.destroy_all
    # return if bracket_entries.present?

    first_round_entries = [
      [ Player.find_by(name: "Jewell Loyd"), Player.bye ],
      [ Player.find_by(name: "Rae Burrell"), Player.find_by(name: "Natasha Cloud") ],
      [ Player.find_by(name: "Alyssa Thomas"), Player.find_by(name: "Azurá Stevens") ],
      [ Player.find_by(name: "Chelsea Gray"), Player.find_by(name: "Shakira Austin") ],
      [ Player.find_by(name: "Napheesa Collier"), Player.find_by(name: "Katie Lou Samuelson") ],
      [ Player.find_by(name: "Jackie Young"), Player.find_by(name: "Rickea Jackson") ],
      [ Player.find_by(name: "Tiffany Hayes"), Player.find_by(name: "Courtney Williams") ],
      [ Player.find_by(name: "Rhyne Howard"), Player.find_by(name: "Lexie Hull") ],
      [ Player.find_by(name: "Breanna Stewart"), Player.find_by(name: "Aaliyah Edwards") ],
      [ Player.find_by(name: "Marina Mabrey"), Player.find_by(name: "Kate Martin") ],
      [ Player.find_by(name: "Allisha Gray"), Player.find_by(name: "Jordin Canada") ],
      [ Player.find_by(name: "Kahleah Copper"), Player.find_by(name: "Aliyah Boston") ],
      [ Player.find_by(name: "Arike Ogunbowale"), Player.bye ],
      [ Player.find_by(name: "Skylar Diggins-Smith"), Player.find_by(name: "Dearica Hamby") ],
      [ Player.find_by(name: "Satou Sabally"), Player.find_by(name: "Brittney Sykes") ],
      [ Player.find_by(name: "Kayla McBride"), Player.find_by(name: "DiJonai Carrington") ]
    ]



    first_round_entries.each do |entry|
      player1 = entry[0]
      player2 = entry[1]

      if player2.bye? || player2.is_out?
        winner = player1
      elsif player1.bye? || player1.is_out?
        winner = player2
      end

      if player1.is_out? && player2.is_out?
        winner = nil
      end


      bracket_entries << BracketEntry.new(
        round: "First Round",
        player1: player1,
        player2: player2,
        actual_winner_id: winner&.id
      )
    end

    # only one can progress, let's generate all empty entries for the Second Round, Quatrer Final, Semi Finals, and Finals
    bracket_entries.first_round.each_slice(2) do |entries|
      first_bracket = entries.first
      second_bracket = entries.second

      player1 = Player.find(first_bracket.actual_winner_id) if first_bracket.actual_winner_id.present?
      player2 = Player.find(second_bracket.actual_winner_id) if second_bracket.actual_winner_id.present?

      # if both of the players are out from either the first_bracket or the second_bracket, then move the first and second players from the bracket forward in the matchup
      if first_bracket.player1.is_out? && first_bracket.player2.is_out?
        player1 = second_bracket.player1
        player2 = second_bracket.player2
      elsif second_bracket.player1.is_out? && second_bracket.player2.is_out?
        player1 = first_bracket.player1
        player2 = first_bracket.player2
      end


      bracket_entries << BracketEntry.new(
        round: "Second Round",
        player1: player1,
        player2: player2,
        previous_entry1_id: entries.first.id,
        previous_entry2_id: entries.second&.id
      )
    end

    bracket_entries.second_round.each_slice(2) do |entries|
      bracket_entries << BracketEntry.new(
        round: "Quarter Finals",
        player1: nil,
        player2: nil,
        previous_entry1_id: entries.first.id,
        previous_entry2_id: entries.second&.id
      )
    end

    bracket_entries.quarter_final.each_slice(2) do |entries|
      bracket_entries << BracketEntry.new(
        round: "Semi Finals",
        player1: nil,
        player2: nil,
        previous_entry1_id: entries.first.id,
        previous_entry2_id: entries.second&.id
      )
    end

    bracket_entries.semi_final.each_slice(2) do |entries|
      bracket_entries <<  BracketEntry.new(
        round: "Final",
        player1: nil,
        player2: nil,
        previous_entry1_id: entries.first.id,
        previous_entry2_id: entries.second&.id
      )
    end

    bracket_entries.final.each_slice(2) do |entries|
      bracket_entries << BracketEntry.new(
        round: "Winner",
        player1: nil,
        player2: nil,
        previous_entry1_id: entries.first.id,
        previous_entry2_id: entries.second&.id
      )
    end


    bracket_entries
  end
end

app/controllers/api/brackets_controller.rb
class Api::BracketsController < ApplicationController
  def create
  end

  def show
    @bracket = Bracket.find(params[:id]).as_json(include: :bracket_entries)

    render json: @bracket
  end
end

app/controllers/brackets_controller.rb
class BracketsController < ApplicationController
  before_action :authorize_user!, only: %i[ update ]


  def index
  end

  def new
    @bracket = Bracket.new
    @bracket.user_identifier = current_user_identifier
    @bracket.save
    @bracket.initial_entries

    redirect_to bracket_path(@bracket)
  end

  def show
    @bracket = Bracket.find(params[:id])
  end

  def update
    @bracket = Bracket.find(params[:id])

    bracket_entries = @bracket.bracket_entries
    entries_to_update = bracket_params[:bracket_entries]

    entries_to_update.each do |entry|
      bracket_entry = bracket_entries.find { |be| be.id == entry[:id] }

      bracket_entry&.update(
        player1_id: entry.dig(:player1, :id),
        player2_id: entry.dig(:player2, :id),
        predicted_winner_id: entry.dig(:predicted_winner, :id)
      )
    end

    render json: { success: true }
  end

  private

  def bracket_params
    params.require(:bracket).permit(:id, bracket_entries: [ :id, :round, :actual_winner_id, :previous_entry1_id, :previous_entry2_id, :parent_bracket_id,   predicted_winner: {}, player1: {}, player2: {}  ])
  end

  def authorize_user!
    @bracket = Bracket.find(params[:id])
    unless @bracket.user_identifier == current_user_identifier
      redirect_to root_path, alert: "You are not authorized to modify this record."
    end
  end
end

app/helpers/api/brackets_helper.rb
module Api::BracketsHelper
end

app/helpers/brackets_helper.rb
module BracketsHelper
end

app/views/brackets/_player.html.erb
<div id="<%= id%> " class="matchup flex justify-between items-center m-1">
    <% if player.present?  %>

    <div class="flex items-center"> 
        <% if player.bye? %>
            <div class="player-card"></div>
        <% else %>
            <%= image_tag("players_transparent/#{player.id}.png", class: "player-card") %>
        <%end %>
        <span class="p-1 text-sm text-left syncopate">
            <span class="font-light"><%= player.first_name %></span>
            <div class="font-black  "><%= player.last_name %></div>
        </span>
     </div>
     <span>
        <span class="text-xs rank px-1 py-1 mr-1">#1</span>
     </span>

    <%else %>
        <div class="flex items-center">
            <div class="player-card"></div>
            <span class="font-black p-1 syncopate text-sm"></span>
        </div>
    <%end%>
</div>

app/views/brackets/index.html.erb
<div class="tournament-container">
  <h1 class="tournament-title syncopate">Unrivaled 1-on-1 Tournament</h1>
<%= link_to "Create Your Bracket", new_bracket_path, class: "btn btn-primary bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
</div>

app/views/brackets/show.html copy.erb
<div id="root"></div>


<div class="tournament-container">
  <h1 class="tournament-title syncopate">Unrivaled 1-on-1 Tournament</h1>
  <div class="bracket">
    <section aria-labelledby="round-1">
      <h2 id="round-2" class="round-title">Round 1</h2>
      <ol>
        <% @bracket.bracket_entries.first_round[0..7].each do |entry| %>
          <li>
            <div>
               <%= entry.id %>

              <%= render partial: 'player', locals: { player: entry.player1, id: entry.previous_entry1_id } %>
              <%= render partial: 'player', locals: { player: entry.player2, id: entry.previous_entry2_id } %>
            </div>
          </li>
        <% end %>
      </ol>
    </section>

    <section aria-labelledby="round-2">
      <h2 id="round-2" class="round-title">Round 2</h2>
      
      <ol >
        <% @bracket.bracket_entries.second_round[0..3].each do |entry| %>
          <li id="<%= @bracket.id%>">
            <div>
              <%= render partial: 'player', locals: { player: entry.player1, id: entry.previous_entry1_id } %>
              <%= render partial: 'player', locals: { player: entry.player2, id: entry.previous_entry2_id } %>
            </div>
          </li>
        <% end %>
      </ol>
    </section>

    <section aria-labelledby="quarter-finals">
      <h2 id="round-2" class="round-title">Quarter Finalss</h2>
      <ol >
        <% @bracket.bracket_entries.quarter_final[0..1].each do |entry| %>
          <li>
            <div>
              <%= render partial: 'player', locals: { player: entry.player1, id: entry.previous_entry1_id } %>
              <%= render partial: 'player', locals: { player: entry.player2, id: entry.previous_entry2_id } %>
            </div>
          </li>
        <% end %>
      </ol>
    </section>

    <section aria-labelledby="semi-finals">
      <h2 id="round-2" class="round-title">Semi Finalss</h2>
      <ol >
        <% entry = @bracket.bracket_entries.semi_final[0] %>
        <li>
          <div>
<%= render partial: 'player', locals: { player: entry.player1, id: entry.previous_entry1_id } %>
              <%= render partial: 'player', locals: { player: entry.player2, id: entry.previous_entry2_id } %>
          </div>
        </li>
      </ol>
    </section>


    <section aria-labelledby="round-2">
      <h2 id="round-2" class="round-title">Round 2</h2>
      <ol >
        <% @bracket.bracket_entries.second_round[4..].each do |entry| %>
          <li id="<%= @bracket.id%>">
            <div>
<%= render partial: 'player', locals: { player: entry.player1, id: entry.previous_entry1_id } %>
              <%= render partial: 'player', locals: { player: entry.player2, id: entry.previous_entry2_id } %>
            </div>
          </li>
        <% end %>
      </ol>
    </section>


    <section aria-labelledby="round-1">
      <h2 class="round-title">Round 1</h2>
      <ol>
        <% @bracket.bracket_entries.first_round[8..-1].each do |entry| %>
          <li>
            <div>
<%= render partial: 'player', locals: { player: entry.player1, id: entry.previous_entry1_id } %>
              <%= render partial: 'player', locals: { player: entry.player2, id: entry.previous_entry2_id } %>
            </div>
          </li>
        <% end %>
      </ol>
    </section>
    
  </div>
</div>

app/views/brackets/show.html.erb
<div id="root"></div>
<div class="my-3 text-sm">
    Hi there! This is a fan-made tournament brackets application.<br/>
    If you have any questions or just like it and want to let me know, here's my Blue Sky<br/>
    <a href="https://bsky.app/profile/corywmcdonald.com" class="text-blue-500 underline">@corywmcdonald.com</a>
</div>